// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

struct Data
{
	float A;
	float B;
	float C;
};

// 从CPU写入进来的数据
StructuredBuffer<Data> inputData;

// 之后写会CPU的数据
RWStructuredBuffer<Data> outputData;

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
	outputData[id.x].A = inputData[id.x].A * 2;
	outputData[id.x].B = inputData[id.x].B * 2;
	outputData[id.x].C = inputData[id.x].C * 2;
}
